project_id = "psupgftxzyoyeyuhtqgw"

[functions.send-push-notification]
verify_jwt = false

[functions.giphy-proxy]
verify_jwt = false

[functions.faktasjekker]
verify_jwt = false

[functions.poll-push]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.broadcast-reinstall]
verify_jwt = false

[functions.notify-admin-new-user]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false
