project_id = "psupgftxzyoyeyuhtqgw"

[functions.send-push-notification]
verify_jwt = false

[functions.weather-engine-refresh]
verify_jwt = false

[functions.weather-engine-get]
verify_jwt = false

[functions.weather-engine-v2]
verify_jwt = false

[functions.weather-engine-v3]
verify_jwt = false

[functions.webcam-proxy]
verify_jwt = false

[functions.giphy-proxy]
verify_jwt = false

[functions.weather-yr]
verify_jwt = false

[functions.weather-meteoswiss]
verify_jwt = false

[functions.weather-ai-summary]
verify_jwt = false