// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get_my_profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Hent min profil",
  description: "Hent den innloggede brukerens G\xFCttaH\xFCtte-profil (navn, kallenavn, avatar, admin-status).",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const [{ data: profile, error }, { data: roles }] = await Promise.all([
      supabase.from("profiles").select("id,email,full_name,nickname,avatar_url,is_active,is_banned,created_at").eq("id", ctx.getUserId()).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", ctx.getUserId())
    ]);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const result = { ...profile, roles: (roles ?? []).map((r) => r.role) };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list_recent_chat.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_chat_default = defineTool2({
  name: "list_recent_chat_messages",
  title: "Nylige chat-meldinger",
  description: "Hent de siste meldingene fra hoved-chatten i G\xFCttaH\xFCtte.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Antall meldinger \xE5 hente (1-100).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("messages").select("id,text,sender_id,sender_name,created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { messages: data }
    };
  }
});

// src/lib/mcp/tools/post_chat_message.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var WELCOME_THREAD_ID = "00000000-0000-0000-0000-000000000001";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var post_chat_message_default = defineTool3({
  name: "post_chat_message",
  title: "Send chat-melding",
  description: "Send en melding til G\xFCttaH\xFCtte-hovedchatten som den innloggede brukeren.",
  inputSchema: {
    text: z2.string().trim().min(1).max(2e3).describe("Meldingsteksten som skal sendes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ text }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const userId = ctx.getUserId();
    const { data: profile } = await supabase.from("profiles").select("nickname,full_name").eq("id", userId).maybeSingle();
    const senderName = profile?.nickname || profile?.full_name || "Ukjent";
    const { data, error } = await supabase.from("messages").insert({ text, thread_id: WELCOME_THREAD_ID, sender_id: userId, sender_name: senderName }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Sendt: "${text}"` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "psupgftxzyoyeyuhtqgw";
var mcp_default = defineMcp({
  name: "guttahutte-mcp",
  title: "G\xFCttaH\xFCtte",
  version: "0.2.0",
  instructions: "Verkt\xF8y for G\xFCttaH\xFCtte-appen. Brukeren logger inn med sin egen konto via OAuth og alle kall kj\xF8rer som den brukeren (RLS gjelder). Bruk `get_my_profile` for egen profil, `list_recent_chat_messages` for \xE5 lese nylige chat-meldinger, og `post_chat_message` for \xE5 sende en melding til gruppechatten.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_recent_chat_default, post_chat_message_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
